name = "backend"
main = "src/index.ts"
compatibility_date = "2024-11-06"

# compatibility_flags = [ "nodejs_compat" ]



[vars]
DATABASE_URL=import.meta.env.VITE_DATABASE_URL
JWT_SECRET = import.meta.env.VITE_JWT_SECRET
EMAILJS_SERVICE_ID=import.meta.env.VITE_EMAILJS_SERVICE_ID
EMAILJS_TEMPLATE_ID=import.meta.env.VITE_EMAILJS_TEMPLATE_ID
EMAILJS_PRIVATE_KEY=import.meta.env.VITE_EMAILJS_PRIVATE_KEY
EMAILJS_PUBLIC_KEY=import.meta.env.VITE_EMAILJS_PUBLIC_KEY